### ISSUE TITLE
OSMetrics

### ISSUE THREAD

**Issue by sabas** [mvexel/OSMQualityMetrics#1]
Hi Martijn,
I made some extensions of your code (which I used to do regional stats at OSMit2012 and OSMit2013 :-) ), if you want to take back something here it is https://github.com/sabas/OSMetrics
Basically I did:
-move the code to different files
-only counting and no shape export
-added some new metrics (road network, buildings,..)
-export in a semicolon separated csv instead of tab separated

**Comment by mvexel** [comment]
Cool! Sorry for the late reply :) I am doing some open source project gardening. If your project is still active, should I point to it in the README?

**Comment by sabas** [comment]
Hi @mvexel, I've used it in 2014 only :)

**Comment by mvexel** [comment]
okay, thanks. Sorry again!
